/* contrib/json_event_stream/json_event_stream--1.0.sql */

-- complain if script is sourced in psql, rather than via CREATE EXTENSION
\echo Use "CREATE EXTENSION json_event_stream" to load this file. \quit

CREATE TABLE json_event_streams (
	stream_table regclass PRIMARY KEY,
	stream_name name NOT NULL,
	partition_interval interval NOT NULL DEFAULT '1 day',
	retention interval,
	payload_gin_enabled boolean NOT NULL DEFAULT false,
	created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
	CONSTRAINT json_event_stream_partition_interval_check
		CHECK (partition_interval > interval '0 seconds')
);

CREATE TABLE json_event_sources (
	source_name name PRIMARY KEY,
	source_type text NOT NULL,
	stream_table regclass NOT NULL REFERENCES json_event_streams(stream_table)
		ON UPDATE CASCADE ON DELETE CASCADE,
	config jsonb NOT NULL DEFAULT '{}'::jsonb,
	enabled boolean NOT NULL DEFAULT true,
	last_seen_at timestamptz,
	last_error text,
	created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
	CONSTRAINT json_event_sources_type_check
		CHECK (source_type IN ('mqtt', 'http'))
);

CREATE TABLE json_event_dead_letters (
	dead_letter_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	stream_table regclass,
	source text NOT NULL,
	topic text,
	received_at timestamptz NOT NULL DEFAULT clock_timestamp(),
	headers jsonb NOT NULL DEFAULT '{}'::jsonb,
	raw_payload text,
	error_code text NOT NULL,
	error_message text NOT NULL
);

CREATE FUNCTION json_event_stream_ensure_partition(
	stream_table regclass,
	event_time timestamptz DEFAULT clock_timestamp()
)
RETURNS regclass
LANGUAGE plpgsql
AS $$
DECLARE
	stream_meta json_event_streams%ROWTYPE;
	parent_schema name;
	parent_name name;
	partition_start timestamptz;
	partition_end timestamptz;
	partition_name name;
	partition_qualified text;
	partition_oid regclass;
BEGIN
	SELECT * INTO stream_meta
	FROM json_event_streams
	WHERE json_event_streams.stream_table = json_event_stream_ensure_partition.stream_table;

	IF NOT FOUND THEN
		RAISE EXCEPTION 'json event stream % is not registered', stream_table;
	END IF;

	SELECT n.nspname, c.relname
	INTO parent_schema, parent_name
	FROM pg_class c
	JOIN pg_namespace n ON n.oid = c.relnamespace
	WHERE c.oid = stream_table;

	partition_start := date_bin(stream_meta.partition_interval, event_time,
		'2000-01-01 00:00:00+00'::timestamptz);
	partition_end := partition_start + stream_meta.partition_interval;
	partition_name := left(parent_name || '_' ||
		to_char(partition_start AT TIME ZONE 'UTC', 'YYYYMMDDHH24MISS'), 63);
	partition_qualified := format('%I.%I', parent_schema, partition_name);
	partition_oid := to_regclass(partition_qualified);

	IF partition_oid IS NULL THEN
		BEGIN
			EXECUTE format(
				'CREATE TABLE %s PARTITION OF %s FOR VALUES FROM (%L) TO (%L)',
				partition_qualified,
				stream_table,
				partition_start,
				partition_end);
		EXCEPTION
			WHEN duplicate_table THEN
				NULL;
		END;

		partition_oid := to_regclass(partition_qualified);
	END IF;

	RETURN partition_oid;
END;
$$;

CREATE FUNCTION json_event_stream_create(
	stream_name name,
	partition_interval interval DEFAULT '1 day',
	retention interval DEFAULT NULL,
	create_payload_gin boolean DEFAULT false
)
RETURNS regclass
LANGUAGE plpgsql
AS $$
DECLARE
	stream_oid regclass;
	first_partition regclass;
BEGIN
	IF partition_interval <= interval '0 seconds' THEN
		RAISE EXCEPTION 'partition_interval must be positive';
	END IF;

	EXECUTE format(
		'CREATE TABLE IF NOT EXISTS %I (
			event_id bigint GENERATED BY DEFAULT AS IDENTITY,
			source text NOT NULL DEFAULT %L,
			topic text NOT NULL,
			received_at timestamptz NOT NULL DEFAULT clock_timestamp(),
			producer_at timestamptz,
			headers jsonb NOT NULL DEFAULT %L::jsonb,
			payload jsonb NOT NULL
		) PARTITION BY RANGE (received_at)',
		stream_name,
		'unknown',
		'{}');

	stream_oid := to_regclass(stream_name::text);

	INSERT INTO json_event_streams (
		stream_table,
		stream_name,
		partition_interval,
		retention,
		payload_gin_enabled
	)
	VALUES (
		stream_oid,
		stream_name,
		partition_interval,
		retention,
		create_payload_gin
	)
	ON CONFLICT (stream_table) DO UPDATE SET
		partition_interval = EXCLUDED.partition_interval,
		retention = EXCLUDED.retention,
		payload_gin_enabled = EXCLUDED.payload_gin_enabled;

	EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %s USING brin (received_at)',
		stream_name || '_received_at_brin_idx',
		stream_oid);
	EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %s (topic)',
		stream_name || '_topic_idx',
		stream_oid);

	IF create_payload_gin THEN
		EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %s USING gin (payload jsonb_path_ops)',
			stream_name || '_payload_gin_idx',
			stream_oid);
	END IF;

	first_partition := json_event_stream_ensure_partition(stream_oid, clock_timestamp());
	RETURN stream_oid;
END;
$$;

CREATE FUNCTION json_event_stream_ingest(
	stream_table regclass,
	source text,
	topic text,
	payload jsonb,
	headers jsonb DEFAULT '{}'::jsonb,
	producer_at timestamptz DEFAULT NULL,
	received_at timestamptz DEFAULT clock_timestamp()
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
	event_id bigint;
BEGIN
	IF source IS NULL OR source = '' THEN
		RAISE EXCEPTION 'source must not be empty';
	END IF;
	IF topic IS NULL OR topic = '' THEN
		RAISE EXCEPTION 'topic must not be empty';
	END IF;
	IF payload IS NULL THEN
		RAISE EXCEPTION 'payload must not be null';
	END IF;

	PERFORM json_event_stream_ensure_partition(stream_table, received_at);

	EXECUTE format(
		'INSERT INTO %s (source, topic, received_at, producer_at, headers, payload)
		 VALUES ($1, $2, $3, $4, COALESCE($5, %L::jsonb), $6)
		 RETURNING event_id',
		stream_table,
		'{}')
	USING source, topic, received_at, producer_at, headers, payload
	INTO event_id;

	UPDATE json_event_sources
	SET last_seen_at = clock_timestamp(),
		last_error = NULL
	WHERE json_event_sources.source_name = json_event_stream_ingest.source
	  AND json_event_sources.stream_table = json_event_stream_ingest.stream_table;

	RETURN event_id;
END;
$$;

CREATE FUNCTION json_event_stream_reject(
	stream_table regclass,
	source text,
	topic text,
	raw_payload text,
	error_code text,
	error_message text,
	headers jsonb DEFAULT '{}'::jsonb,
	received_at timestamptz DEFAULT clock_timestamp()
)
RETURNS bigint
LANGUAGE SQL
AS $$
	INSERT INTO json_event_dead_letters (
		stream_table,
		source,
		topic,
		received_at,
		headers,
		raw_payload,
		error_code,
		error_message
	)
	VALUES ($1, $2, $3, $8, COALESCE($7, '{}'::jsonb), $4, $5, $6)
	RETURNING dead_letter_id;
$$;

CREATE FUNCTION json_event_mqtt_source_create(
	source_name name,
	broker_uri text,
	topic_filter text,
	stream_table regclass,
	config jsonb DEFAULT '{}'::jsonb,
	enabled boolean DEFAULT true
)
RETURNS name
LANGUAGE SQL
AS $$
	INSERT INTO json_event_sources (
		source_name,
		source_type,
		stream_table,
		config,
		enabled
	)
	VALUES (
		$1,
		'mqtt',
		$4,
		jsonb_build_object('broker', $2, 'topic', $3) || COALESCE($5, '{}'::jsonb),
		$6
	)
	ON CONFLICT (source_name) DO UPDATE SET
		stream_table = EXCLUDED.stream_table,
		config = EXCLUDED.config,
		enabled = EXCLUDED.enabled
	RETURNING source_name;
$$;

CREATE FUNCTION json_event_http_source_create(
	source_name name,
	route text,
	stream_table regclass,
	config jsonb DEFAULT '{}'::jsonb,
	enabled boolean DEFAULT true
)
RETURNS name
LANGUAGE SQL
AS $$
	INSERT INTO json_event_sources (
		source_name,
		source_type,
		stream_table,
		config,
		enabled
	)
	VALUES (
		$1,
		'http',
		$3,
		jsonb_build_object('route', $2) || COALESCE($4, '{}'::jsonb),
		$5
	)
	ON CONFLICT (source_name) DO UPDATE SET
		stream_table = EXCLUDED.stream_table,
		config = EXCLUDED.config,
		enabled = EXCLUDED.enabled
	RETURNING source_name;
$$;

CREATE FUNCTION json_event_stream_set_retention(
	stream_table regclass,
	retention interval
)
RETURNS void
LANGUAGE SQL
AS $$
	UPDATE json_event_streams
	SET retention = $2
	WHERE stream_table = $1;
$$;

CREATE FUNCTION json_event_stream_apply_retention(
	stream_table regclass DEFAULT NULL,
	dry_run boolean DEFAULT true
)
RETURNS TABLE(stream regclass, partition regclass, partition_to timestamptz, would_drop boolean)
LANGUAGE plpgsql
AS $$
DECLARE
	part record;
BEGIN
	FOR part IN
		SELECT
			s.stream_table,
			child.oid::regclass AS partition_table,
			pg_get_expr(child.relpartbound, child.oid)::text AS part_bound,
			s.retention
		FROM json_event_streams s
		JOIN pg_inherits i ON i.inhparent = s.stream_table
		JOIN pg_class child ON child.oid = i.inhrelid
		WHERE s.retention IS NOT NULL
		  AND (json_event_stream_apply_retention.stream_table IS NULL
			   OR s.stream_table = json_event_stream_apply_retention.stream_table)
	LOOP
		partition_to := substring(part.part_bound FROM 'TO \(''([^'']+)''\)')::timestamptz;
		stream := part.stream_table;
		partition := part.partition_table;
		would_drop := partition_to < clock_timestamp() - part.retention;

		IF would_drop AND NOT dry_run THEN
			EXECUTE format('DROP TABLE %s', part.partition_table);
		END IF;

		RETURN NEXT;
	END LOOP;
END;
$$;

CREATE FUNCTION json_event_stream_add_payload_path_index(
	stream_table regclass,
	index_name name,
	json_path text
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
	EXECUTE format(
		'CREATE INDEX IF NOT EXISTS %I ON %s ((payload #>> %L))',
		index_name,
		stream_table,
		string_to_array(json_path, '.'));
END;
$$;

CREATE VIEW json_event_ingestion_status AS
SELECT
	src.source_name,
	src.source_type,
	src.stream_table,
	src.enabled,
	src.config,
	src.last_seen_at,
	src.last_error,
	clock_timestamp() - src.last_seen_at AS ingestion_lag
FROM json_event_sources src;

CREATE VIEW json_event_rejected_messages AS
SELECT
	dead_letter_id,
	stream_table,
	source,
	topic,
	received_at,
	error_code,
	error_message,
	headers,
	raw_payload
FROM json_event_dead_letters;

CREATE VIEW json_event_partition_status AS
SELECT
	s.stream_table,
	child.oid::regclass AS partition_table,
	pg_get_expr(child.relpartbound, child.oid) AS partition_bound,
	pg_total_relation_size(child.oid) AS total_bytes,
	s.retention
FROM json_event_streams s
JOIN pg_inherits i ON i.inhparent = s.stream_table
JOIN pg_class child ON child.oid = i.inhrelid;

CREATE VIEW json_event_index_recommendations AS
SELECT
	s.stream_table,
	CASE
		WHEN NOT s.payload_gin_enabled THEN 'Consider a payload GIN index for jsonpath predicates.'
		ELSE 'Payload GIN index requested for this stream.'
	END AS recommendation
FROM json_event_streams s;
